<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>StarDust.CasparCG.Protocol.Amcp</AssemblyName>
    <RootNamespace>StarDust.CasparCG.Protocol.Amcp</RootNamespace>
  </PropertyGroup>
</Project>
