name: package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          cache: true
      - run: dotnet pack src/StarDust.CasparCG/StarDust.CasparCG.csproj -p:BuildInParallel=false --configuration Release -o artifacts/packages
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
